'use client';

import React from 'react';
import { Mic, Volume2, Sparkles, CheckCircle2, TrendingUp } from 'lucide-react';

export default function TeacherAIReviewPage() {
  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      <div className="p-6 rounded-3xl bg-white border border-slate-200 shadow-xs">
        <span className="px-2.5 py-0.5 rounded-full bg-blue-50 text-blue-600 text-xs font-bold uppercase">
          AI Speech & Writing Review
        </span>
        <h1 className="text-2xl font-black text-slate-900 mt-1">AI Speech & Pronunciation Audits</h1>
        <p className="text-xs text-slate-500 font-medium">Inspect raw microphone recordings and phonetics accuracy generated by AI speech models.</p>
      </div>

      <div className="p-6 rounded-3xl bg-white border border-slate-200 space-y-4 shadow-xs">
        <div className="flex justify-between items-center">
          <div>
            <h3 className="text-base font-bold text-slate-900">Student: David Smith (USA 🇺🇸)</h3>
            <p className="text-xs text-slate-500">Audio Prompt: &quot;नमस्ते! मेरा नाम डेविड है।&quot;</p>
          </div>
          <span className="px-3 py-1 rounded-full bg-emerald-50 text-emerald-600 text-xs font-bold">
            Phonetics Score: 94%
          </span>
        </div>

        <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200 text-xs text-slate-700 flex items-center justify-between">
          <span>AI Audio Stream: Recording #8820 (3.2 seconds)</span>
          <button className="px-3 py-1.5 rounded-lg bg-blue-600 text-white font-bold text-xs flex items-center gap-1">
            <Volume2 className="w-3.5 h-3.5" /> Play Audio Recording
          </button>
        </div>
      </div>
    </div>
  );
}
